# Generated by Django 3.1.4 on 2021-01-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=150, verbose_name='Department')),
                ('stage', models.CharField(max_length=150, null=True, verbose_name='Stage')),
                ('assigned', models.BooleanField(default=False, verbose_name='Assigned')),
                ('team', models.CharField(max_length=120, null=True, verbose_name='Team')),
                ('Date', models.DateField(verbose_name='Date')),
                ('Status', models.CharField(max_length=150, verbose_name='Status')),
                ('Action', models.CharField(max_length=150, null=True, verbose_name='Action')),
            ],
        ),
    ]
